# Generated by Django 3.2.8 on 2021-10-31 20:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TradeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeType', models.CharField(max_length=10)),
                ('ideaName', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=20)),
                ('target', models.IntegerField()),
                ('stopLoss', models.IntegerField()),
                ('createdAt', models.TimeField(default=datetime.datetime.now)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeIdeaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.tradeidea')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
